### ISSUE TITLE
Does not account for flying in spectator mode

### ISSUE THREAD

**Issue by Friskygote** [tired9494/Flight-Rings#1]
Hello!

I've noticed mod doesn't account for flying in spectator mode, in https://github.com/tired9494/Flight-Rings/blob/f07cad51ecf601fc82d10d4697b980a25e6db08b/src/main/java/flight_rings/flight_rings/rings/AdvancedRing.java#L98 there is an exception for creative mode however none for spectator mode which results in noclip falling into void and dying. 

By the way, thank you for creating the mod!

**Comment by tired9494** [comment]
Thank you,
this has been fixed in 1.4.2
